version: '3'

services:
  signaling:
    build: .
    image: poc-video-call-server
    # ports:
    #   - 8100:8100
    expose:
      - 8100
    environment:
      - VIRTUAL_HOST=client.ccd.dev.scale360.solutions

  proxy:
    image: jwilder/nginx-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/letsencrypt/live/client.ccd.dev.scale360.solutions:/etc/nginx/certs